# Generated by Django 2.2.6 on 2019-11-07 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='img',
            name='cmpScore',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='img',
            name='like',
            field=models.IntegerField(null=True),
        ),
    ]
